export const FETCH_CLASSES_START = 'FETCH_CLASSES_START',
  FETCH_CLASSES_SUCCESS = 'FETCH_CLASSES_SUCCESS',
  FETCH_CLASSES_FAILURE = 'FETCH_CLASSES',
  ADD_CLASS = 'ADD_CLASS',
  DELETE_CLASS = 'DELETE_CLASS',
  EDIT_CLASS = 'EDIT_CLASS';
