export const FETCH_ATTENDANCE_START = 'FETCH_ATTENDANCE_START',
  FETCH_ATTENDANCE_SUCCESS = 'FETCH_ATTENDANCE_SUCCESS',
  FETCH_ATTENDANCE_FAILURE = 'FETCH_ATTENDANCE_FAILURE',
  FETCH_ATTENDANCE_FOR_COURSE = 'FETCH_ATTENDANCE_FOR_COURSE';
