export const FETCH_ATTENDANCE_START = 'FETCH_ATTENDANCE_START',
  FETCH_ATTENDANCE_SUCCESS = 'FETCH_ATTENDANCE_SUCCESS',
  FETCH_ATTENDANCE_FAILURE = 'FETCH_ATTENDANCE_FAILURE',
  SET_CURRENT_COURSE = 'SET_CURRENT_COURSE',
  SET_CURRENT_DATE = 'SET_CURRENT_DATE',
  ADD_COURSE_ATTENDANCE_SUCCESS = 'ADD_COURSE_ATTENDANCE_SUCCESS',
  DELETE_COURSE_ATTENDANCE_SUCCESS = 'DELETE_COURSE_ATTENDANCE_SUCCESS',
  UPDATE_ATTENDANCE_SUCCESS = 'UPDATE_ATTENDANCE_SUCCESS',
  UPDATE_STUDENT_ATTENDANCE_STATUS_START =
    'UPDATE_STUDENT_ATTENDANCE_STATUS_START',
  UPDATE_STUDENT_ATTENDANCE_STATUS_SUCCESS =
    'UPDATE_STUDENT_ATTENDANCE_STATUS_SUCCESS',
  UPDATE_STUDENT_ATTENDANCE_STATUS_FAILURE =
    'UPDATE_STUDENT_ATTENDANCE_STATUS_FAILURE';
